version: "3.5"
services:
  keycloak-proxy:
    image: jboss/keycloak-proxy
    ports:
      - "3001:3001"
    volumes:
      - "./keycloak-proxy.json:/opt/jboss/conf/proxy.json"
    networks:
      - dory-network


networks:
    dory-network: