version: "3.5"
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - "8080:8080" 
      - "50000:50000"
    networks:
      - usine-network

  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "thor"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://thor"
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - "80:80"
      - "2224:22"
    volumes:
      - "./data/gitlab/config:/etc/gitlab"
      - "./data/gitlab/logs:/var/log/gitlab"
      - "./data/gitlab/data:/var/opt/gitlab"
    networks:
      - usine-network

  nexus:
    image: "sonatype/nexus3"
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - "nexus-data:/nexus-data"
    networks:
      - usine-network

volumes:
 nexus-data:

networks:
    usine-network: