version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - "8080:8080" 
      - "50000:50000"
